### ISSUE TITLE
we can't get it working

### ISSUE THREAD

**Issue by MarkTheFreak** [OpenShopChannel/Open-Shop-SOAP#2]
the soap is too soapy we need assistance

**Comment by dhtdht020** [comment]
We don't plan to fix the soapy soap. Sorry.

**Comment by MarkTheFreak** [comment]
Please it too soapy. Someone could die from it.

**Comment by dhtdht020** [comment]
I see.

**Comment by dhtdht020** [comment]
Fixed! the soap is no longer soapy.

**Comment by dhtdht020** [comment]
readded
we count it as a feature now
