### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by DoshinTehGiant** [OpenShopChannel/Open-Shop-SOAP#3]
Theres an issue here, I T S  N O T  O U T

**Comment by Puppercino** [comment]
If you don’t want to wait for the release of OSC, you can grab a copy of WSC and patch your own WAD to your own servers. 😄

**Comment by Dinosaurismus** [comment]
I tried that, but my Wii exploded when I ran it.

**Comment by dakrk** [comment]
pls

**Comment by Oxygemo** [comment]
@caution3  is right.

**Comment by loparate** [comment]
Poo Poo On My Pee Pee

**Comment by loparate** [comment]
Can I pee on you?
