### ISSUE TITLE
(how) does this work?

### ISSUE THREAD

**Issue by Vinchethescript** [OpenShopChannel/Open-Shop-SOAP#4]

**Comment by elsalamus** [comment]
No

**Comment by Puppercino** [comment]
Open Shop SOAP simply contains blank templates for SOAP that Wii Shop Channel used. 
It is not a program and therefore does not work on its own. 
These were used by WSC to communicate with Nintendo's servers.

**Comment by Vincysuper07** [comment]
> No

You stfu

**Comment by Vinchethescript** [comment]
> Open Shop SOAP simply contains blank templates for SOAP that Wii Shop Channel used. 
> It is not a program and therefore does not work on its own. 
> These were used by WSC to communicate with Nintendo's servers. 

Ok, thank you
